### PR TITLE
Write about the Docker official images build system

### PR DESCRIPTION
**Pull request by JayH5**

### CODE REVIEW

**Review by jerith — APPROVED** [review]
:+1:

**Comment by zoidyzoidzoid** [comment]
I'm not sure where this should be mentioned or if it's worth mentioning but the automated build Docker Hub links are also weird since they only track repo's and not the actual tags used by your images or in the Dockerfile's that it is building.

> Link your Automated Build to another Docker Hub repository, and when that repository is updated, it will automatically trigger a rebuild of this Automated Build.

**Comment by JayH5** [comment]
@zoidbergwill do you mean that Docker Hub automated builds will build any commit that is pushed to the repo, whether or not the commit changes what will be built in the image? And I guess this means some rebuilds could be triggered on a linked repository when nothing has actually changed in the upstream repo?

I haven't actually used "links" in a long time so I'd want to check if that is the behaviour.

**Comment by JayH5** [comment]
Merging for now... automated builds question belongs elsewhere.

**Pull request merged**
